# Generated by Django 4.1.7 on 2023-02-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35, verbose_name='слово')),
                ('word_en', models.CharField(max_length=20, verbose_name='слово на английском')),
                ('definition', models.TimeField(verbose_name='строгое определение')),
            ],
            options={
                'verbose_name': 'ключевое слово',
                'verbose_name_plural': 'ключевые слова',
            },
        ),
        migrations.CreateModel(
            name='ResourceLern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название курса')),
                ('url', models.URLField(verbose_name='Ссылка на курс')),
            ],
            options={
                'verbose_name': 'ссылка на курс',
                'verbose_name_plural': 'ссылки на курсы',
            },
        ),
        migrations.CreateModel(
            name='ResourceStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название ресурса')),
                ('url', models.URLField(verbose_name='Ссылка на ресурс')),
            ],
            options={
                'verbose_name': 'ссылка на ресурс по теме',
                'verbose_name_plural': 'ссылки на ресурсы',
            },
        ),
        migrations.CreateModel(
            name='Topik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Краткое название темы')),
                ('name_en', models.CharField(max_length=20, verbose_name='краткое название на английском')),
                ('description', models.TimeField(verbose_name='тезисное описание или определение темы')),
                ('current_level', models.SmallIntegerField(default=0, verbose_name='Текущий уровень знаний')),
            ],
            options={
                'verbose_name': 'тема обсуждения и изучения',
                'verbose_name_plural': 'темы обсуждения и изучения',
            },
        ),
    ]
