# Generated by Django 4.1.7 on 2023-02-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название дорожной карты')),
                ('name_en', models.CharField(max_length=20, verbose_name='Название плана изучения на английском')),
                ('description', models.TextField(verbose_name='Краткое описание: цели и задачи, сроки, основные темы')),
            ],
            options={
                'verbose_name': 'план изучения',
                'verbose_name_plural': 'планы изучения',
            },
        ),
        migrations.AlterField(
            model_name='keyword',
            name='definition',
            field=models.TextField(verbose_name='строгое определение'),
        ),
    ]
