# Generated by Django 4.1.7 on 2023-02-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_roadmap_alter_keyword_definition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoadMap',
            new_name='RoadMapStudy',
        ),
    ]
