# Generated by Django 4.1.7 on 2023-02-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_rename_roadmap_roadmapstudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=35, verbose_name='кратко сформированный вопрос')),
                ('answer', models.TextField(verbose_name='Развернутый ответ на вопрос')),
            ],
            options={
                'verbose_name': 'часто задаваемый вопрос',
                'verbose_name_plural': 'часто задаваемые вопросы',
            },
        ),
        migrations.AlterModelOptions(
            name='resourcelern',
            options={'verbose_name': 'ссылка на курс', 'verbose_name_plural': 'ссылку на курсы'},
        ),
        migrations.AlterModelOptions(
            name='resourcestudy',
            options={'verbose_name': 'ссылка на ресурс по теме', 'verbose_name_plural': 'ссылку на ресурсы'},
        ),
        migrations.AlterModelOptions(
            name='topik',
            options={'verbose_name': 'тема обсуждения и изучения', 'verbose_name_plural': 'тему обсуждения и изучения'},
        ),
        migrations.AlterField(
            model_name='topik',
            name='description',
            field=models.TextField(verbose_name='тезисное описание или определение темы'),
        ),
    ]
