# Generated by Django 4.1.7 on 2023-03-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_alter_resourcelern_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmapstudy',
            options={'verbose_name': 'план изучения (roadmap)', 'verbose_name_plural': 'планы изучения (roadmaps)'},
        ),
        migrations.AddField(
            model_name='keyword',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='roadmap.topik', verbose_name='ключевые слова'),
        ),
        migrations.AddField(
            model_name='resourcelern',
            name='topik',
            field=models.ManyToManyField(blank=True, null=True, to='roadmap.topik', verbose_name='тема обучения'),
        ),
        migrations.AddField(
            model_name='resourcestudy',
            name='topik',
            field=models.ManyToManyField(blank=True, null=True, to='roadmap.topik', verbose_name='тема обучения'),
        ),
        migrations.AlterField(
            model_name='roadmapstudy',
            name='description',
            field=models.TextField(help_text='цели и задачи, сроки, основные темы', verbose_name='Краткое описание:'),
        ),
        migrations.RemoveField(
            model_name='topik',
            name='roadmap',
        ),
        migrations.AddField(
            model_name='topik',
            name='roadmap',
            field=models.ManyToManyField(blank=True, null=True, to='roadmap.roadmapstudy', verbose_name='план изучения (roadmap)'),
        ),
    ]
