# Generated by Django 4.1.7 on 2023-03-02 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0008_alter_keyword_word_alter_roadmapstudy_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topik',
            options={'verbose_name': 'тема для изучения', 'verbose_name_plural': 'темы для изучения'},
        ),
        migrations.RemoveField(
            model_name='topik',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='topik',
            name='resourcestudy',
        ),
        migrations.RemoveField(
            model_name='resourcelern',
            name='topik',
        ),
        migrations.AlterField(
            model_name='topik',
            name='description',
            field=models.TextField(help_text='тезисное описание или определение темы', verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='name',
            field=models.CharField(max_length=35, verbose_name='название темы'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='name_en',
            field=models.CharField(help_text='название на английском', max_length=20, verbose_name='topik'),
        ),
        migrations.AddField(
            model_name='resourcelern',
            name='topik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadmap.topik', verbose_name='тема обучения'),
        ),
    ]
