# Generated by Django 4.1.7 on 2023-03-02 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0009_alter_topik_options_remove_topik_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название темы')),
                ('name_en', models.CharField(help_text='название на английском', max_length=20, verbose_name='subject')),
                ('description', models.TextField(help_text='описать основные цели и задачи изучаемой темы', verbose_name='цели и задачи темы')),
            ],
            options={
                'verbose_name': 'Тема для изучения',
                'verbose_name_plural': 'Темы для изучения',
            },
        ),
        migrations.AlterModelOptions(
            name='topik',
            options={'verbose_name': 'курс для изучения', 'verbose_name_plural': 'курсы для изучения'},
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='topik',
            name='current_level',
            field=models.SmallIntegerField(default=0, verbose_name='текущий уровень знаний'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='description',
            field=models.TextField(help_text='тезисное описание или цели курса', verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='name',
            field=models.CharField(max_length=35, verbose_name='название курса'),
        ),
        migrations.DeleteModel(
            name='ResourceLern',
        ),
        migrations.AddField(
            model_name='subject',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='roadmap.keyword', verbose_name='ключевые слова'),
        ),
        migrations.AddField(
            model_name='subject',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadmap.resourcestudy'),
        ),
        migrations.AddField(
            model_name='subject',
            name='topik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadmap.topik', verbose_name='курс обучения'),
        ),
    ]
