# Generated by Django 4.1.7 on 2023-03-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0010_subject_alter_topik_options_remove_keyword_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='study_level',
            field=models.FloatField(default=1, help_text='уровень обучения (для сортировки)', verbose_name='уровень обучения'),
            preserve_default=False,
        ),
    ]
