# Generated by Django 4.1.7 on 2023-03-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0011_subject_study_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='study_level',
        ),
        migrations.RemoveField(
            model_name='topik',
            name='current_level',
        ),
        migrations.AddField(
            model_name='subject',
            name='current_level',
            field=models.SmallIntegerField(default=0, verbose_name='текущий уровень знаний'),
        ),
        migrations.AddField(
            model_name='topik',
            name='study_level',
            field=models.FloatField(default=1, help_text='уровень обучения (для сортировки)', verbose_name='уровень обучения'),
        ),
    ]
